default_platform(:ios)

platform :ios do
  desc "Собрать и отправить билд в TestFlight"
  lane :beta do
    api_key = app_store_connect_api_key(
      key_id: "4F67HCB9N8",
      issuer_id: "08ac18d7-d3c1-49a2-901b-6956daadbeb7",
      key_filepath: "./fastlane/AuthKey_4F67HCB9N8.p8"
    )

    update_project_team(
      path: "TamaleTrack.xcodeproj",
      teamid: "NGP65SQNNL"
    )

    automatic_code_signing(
      use_automatic_signing: true,
      path: "TamaleTrack.xcodeproj"
    )

    build_app(
      scheme: "TamaleTrack",
      export_method: "app-store",
      export_options: {
        provisioningProfiles: {
          "com.TamaleTrack" => "match AppStore com.TamaleTrack"
        },
        signingStyle: "automatic",
        signingCertificate: "Apple Distribution",
        compileBitcode: true,
        manageAppVersionAndBuildNumber: true,
      },
      allowProvisioningUpdates: true
    )

    upload_to_testflight(api_key: api_key)
  end
end

