default_platform(:ios)

platform :ios do
  desc "Собрать и залить билд в TestFlight"
  lane :release do
    api_key = app_store_connect_api_key(
        key_id: "4F67HCB9N8",
        issuer_id: "08ac18d7-d3c1-49a2-901b-6956daadbeb7",
        key_filepath: "fastlane/AuthKey_4F67HCB9N8.p8"
    )

    automatic_code_signing(
      use_automatic_signing: true,
      path: "TamaleTrack.xcodeproj"
    )

    build_app(
      scheme: "TamaleTrack",
      export_method: "app-store",
      export_options: {
        signingStyle: "automatic"
      }
    )

    upload_to_testflight(api_key: api_key)
  end

  lane :beta do
    release
  end
end

